### ISSUE TITLE
New logic for setting attributes in package.json & config.xml (§3)

### ISSUE THREAD

**Issue by raphinesse** [apache/cordova-create#22]
_From @raphinesse on July 5, 2018 8:25_

I'm talking about the logic behind setting the appropriate fields for *App ID*,
*App Name* and *App Version* in the files `package.json` and `config.xml`.

### Current situation

The most common strategy is to set the attribute in both files iff a value for
it was given to `cordovaCreate`. Exceptions are
- *App ID in `package.json`*: set attribute if value given else set to `helloworld`
- *App Version in both files*: always set to `1.0.0`

#### Pain Points
- Strategies employed for setting the attributes differ
- Falling back to hard coded defaults is not very flexible (e.g. I usually start my version numbering at `0.1.0`)

### Proposal

For every file `f` and every attribute `attr`, do the following
```js
if (attr in opts) {
    // Save attribute value passed to cordovaCreate to f
    f[attr] = opts[attr]
} else if (attr in f) {
    // Attribute already present in f and no override specified
    // => Leave the existing value untouched
} else if (isRequired(attr, f)) {
    handleMissingRequiredAttribute(attr, f)
}
```
where `isRequired` would have to be defined adequately
and `handleMissingRequiredAttribute` could either:
1. Throw an error (my preference)
2. Save some hard coded fallback value to `f` (possibly warn that `f` is invalid)

### Related issues
[CB-12274 - widget version number not copied from template config.xml file](https://issues.apache.org/jira/browse/CB-12274)

---

Migrated from apache/cordova-discuss#89

_Copied from original issue: apache/cordova-discuss#100_

**Comment by dpogue** [comment]
For the record, currently I do not believe Cordova looks at package.json for an app ID or app version, it expects those to only live in config.xml on the `widget` tag. So setting them in package.json is nice from a consistency perspective, but doesn't actually impact Cordova behaviour.

I think that's fine the way it is, we shouldn't attempt to move those out of config.xml at this point.

**Comment by dpogue** [comment]
If we're creating a new project, then yeah, it makes sense to set the name and version in package.json as well.

What I don't want to do (at this point anyways) is make changes to cordova-lib to read those values out of package.json instead of config.xml.

**Comment by raphinesse** [comment]
@dpogue Alright, the latter was never intended
