### ISSUE TITLE
Cordova create fails if installed with "@" in the path

### ISSUE THREAD

**Issue by simpleigh** [apache/cordova-create#34]
### Environment

Tested on Ubuntu (18.04.1), but the same issue is occurring on Mac.
Cordova version `8.1.2 (cordova-lib@8.1.1)`

### Steps to reproduce

```bash
mkdir build@2
cd build@2
npm install cordova
node_modules/.bin/cordova create hello com.example.hello HelloWorld
```

### What happens

```
Creating a new cordova project.
Unhandled "error" event. (  Error from Cordova Fetch: Error: npm: Command failed with exit code 1 Error output:
npm ERR! code ENOLOCAL
npm ERR! Could not install "../build@2/node_modules/cordova/node_modules/cordova-app-hello-world/index.js" as it is not a directory and is not a file with a name ending in .tgz, .tar.gz or .tar

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-05T15_21_50_141Z-debug.log)
```

### Why this happens

1. Cordova create wants to use the default template at `../build@2/node_modules/cordova/node_modules/cordova-app-hello-world/index.js`
1. It uses `isRemoteUri()` [[source](https://github.com/apache/cordova-create/blob/5e3aab6/index.js#L357-L359)] to determine whether the template location is a local path or remote URI. This notices the `@` and decides it's a remote URI.
1. Because the tempalte location is detected as remote, Cordova-create uses NPM to try and install it [[source](https://github.com/apache/cordova-create/blob/5e3aab6/index.js#L135-L139)].
1. NPM chokes on the path as it isn't a directory or tarball.

### Why this matters

We ran into this while automatically building Cordova projects using Jenkins.
* We're using a local installation of Cordova (not `npm add --global`) so we can easily pin different versions for each separate project and keep project configuration local to each Jenkins workspace.
* Jenkins uses `@` to split workspaces when running multiple concurrent builds. See `hudson.slaves.WorkspaceList` under https://wiki.jenkins.io/display/JENKINS/Features+controlled+by+system+properties.

We can work around the problem by reconfiguring Jenkins, but it feels like others will probably run into this problem. Is there a reason why paths with `@` are automatically assumed to be remote, even if they exist on the filesystem?

**Comment by raphinesse** [comment]
It is a known bug (it has been discussed before; I can't remember where though).
IIRC, my big `cordova-create` refactoring fixed that bug in passing, but the breaking changes that came with it were never accepted.

The bug originates in this function:
https://github.com/apache/cordova-create/blob/5e3aab6369c195512ca31a6134b96446452c5c5a/index.js#L357-L359

A fix might be as easy as replacing the middle partwith `path.basename(uri).includes('@')`

**Comment by wordragon** [comment]
I encountered this following the instructions to "build my first app" - node installed itself with "node@6" in the directory path.  I didn't find the function Raphael posted, but I did use his fix in the same cordova-create/index.js file:

```
//            isNPM = cfg.lib.www.template && (cfg.lib.www.url.indexOf('@') > -1 || !fs.existsSync(path.resolve(cfg.lib.www.url))) && !isGit;
            isNPM = cfg.lib.www.template && (path.basename(cfg.lib.www.url).includes('@') || !fs.existsSync(path.resolve(cfg.lib.www.url))) && !isGit;

```

**Comment by dabing1205** [comment]
works well with raphinesse's workaround. Thanks
