### ISSUE TITLE
Npm tmp dependency version ^0.2.1 breaks cordova install on node 12

### ISSUE THREAD

**Issue by JellyfishDaydreams** [apache/cordova-create#89]
# Bug Report

## Problem
 The `tmp` package is required at ^0.2.1 by cordova-create, and this effectively breaks cordova 11 (maybe others?) on node 12. Yes, that is an ancient version of node, but here we are.

### What is expected to happen?
Installation of cordova 11 on node 12 should install without errors.

### What does actually happen?
The following error is thrown:
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for tmp@0.2.3: wanted: {"node":">=14.14"} (current: {"node":"12.22.12","npm":"6.14.16"})
npm ERR! notsup Not compatible with your version of node/npm: tmp@0.2.3
npm ERR! ..

## Information
This can be overridden locally with an `overrides` entry in package.json, but tightening up the version of tmp used to "tmp": "0.2.1" would be helpful since "^0.2.1" allows the breaking change in. 

### Command or Code

Attempt to install cordova@11 using node 12. 

### Environment, Platform, Device

Node 12. 

### Version information

Cordova 11.1

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by JellyfishDaydreams** [comment]
If this is an acceptable proposed change, I would be happy to put up a PR for this!

**Comment by dpogue** [comment]
The current version of Cordova only supports node 16 and higher. Upcoming releases will only support node 18 and higher, in line with upstream nodeJS deprecations.
